services: 
  app:
    image: nodejs-todo  
    ports: 
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todoappDB
    depends_on:
      - mysql

  mysql:
    image: mysql:9.3
    volumes: 
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todoappDB

volumes: 
  todo-mysql-data:
  